services:
    postgres:
      image: postgres:16-alpine
      ports:
        - "5432:5432"
      environment:
        POSTGRES_DB: backoffice
        POSTGRES_USER: backoffice
        POSTGRES_PASSWORD: backoffice
      volumes:
        - pgdata:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U backoffice -d backoffice"]
        interval: 5s
        timeout: 5s
        retries: 5
  
    minio:
      image: minio/minio:latest
      command: server /data --console-address ":9001"
      ports:
        - "9000:9000"   # API S3
        - "9001:9001"   # console web
      environment:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin
      volumes:
        - miniodata:/data
  
    # cria bucket "backoffice" na subida
    minio-init:
      image: minio/mc:latest
      depends_on:
        minio:
          condition: service_started
      entrypoint:
        - /bin/sh
        - -c
        - |
          mc alias set local http://minio:9000 minioadmin minioadmin &&
          mc mb -p local/backoffice || true
  
volumes:
  pgdata:
  miniodata: