include:
  - docker-compose.yml

services:
  backoffice-native:
    image: backoffice:native-local
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native-micro
    ports:
      - "8080:8080"
    env_file:
      - native-local.env
    depends_on:
      postgres:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    restart: unless-stopped
