package backoffice.common.config;

import io.quarkus.runtime.annotations.RegisterForReflection;

@RegisterForReflection(classNames = {
    "backoffice.v1.dtos.auth.AuthCreateDTO",
    "backoffice.v1.dtos.auth.AuthDTO",
    "backoffice.v1.dtos.auth.AuthExtDTO",
    "backoffice.v1.dtos.benefit.BenefitCreateDTO",
    "backoffice.v1.dtos.benefit.BenefitDTO",
    "backoffice.v1.dtos.benefit.BenefitUpdateDTO",
    "backoffice.v1.dtos.billing.ListSubscriberBillingQueryDTO",
    "backoffice.v1.dtos.billing.ListSubscriberPaymentEventsQueryDTO",
    "backoffice.v1.dtos.billing.SubscriberBillingListResultDTO",
    "backoffice.v1.dtos.billing.SubscriberBillingListStatusFilter",
    "backoffice.v1.dtos.billing.SubscriberBillingRowDTO",
    "backoffice.v1.dtos.billing.SubscriberBillingSummaryDTO",
    "backoffice.v1.dtos.billing.SubscriberMemberConfigSnapshot",
    "backoffice.v1.dtos.billing.SubscriberPaymentEventDTO",
    "backoffice.v1.dtos.billing.SubscriberPaymentMarkPaidDTO",
    "backoffice.v1.dtos.common.ManyReferencesDTO",
    "backoffice.v1.dtos.common.PageDTO",
    "backoffice.v1.dtos.member.ListMembersQueryDTO",
    "backoffice.v1.dtos.member.MemberCreateDTO",
    "backoffice.v1.dtos.member.MemberDataCreateDTO",
    "backoffice.v1.dtos.member.MemberDataUpdateDTO",
    "backoffice.v1.dtos.member.MemberDTO",
    "backoffice.v1.dtos.member.SponsoredDataCreateDTO",
    "backoffice.v1.dtos.member.SponsoredMemberDTO",
    "backoffice.v1.dtos.member.SubscriberDataCreateDTO",
    "backoffice.v1.dtos.member.SubscriberMemberDTO",
    "backoffice.v1.dtos.member.SubscriberMemberUpdateDTO",
    "backoffice.v1.dtos.publics.ListPublicSponsorsQueryDTO",
    "backoffice.v1.dtos.publics.PublicSponsorDataDTO",
    "backoffice.v1.dtos.publics.PublicSponsorItemDTO",
    "backoffice.v1.dtos.publics.PublicSponsorUserDTO",
    "backoffice.v1.dtos.sponsor.SponsorCreateDTO",
    "backoffice.v1.dtos.sponsor.SponsorDataCreateDTO",
    "backoffice.v1.dtos.sponsor.SponsorDataUpdateDTO",
    "backoffice.v1.dtos.sponsor.SponsorDTO",
    "backoffice.v1.dtos.sponsor.SponsorMinDTO",
    "backoffice.v1.dtos.sponsor.SponsorUpdateDTO",
    "backoffice.v1.dtos.upload.UploadConfirmDTO",
    "backoffice.v1.dtos.upload.UploadConfirmResponseDTO",
    "backoffice.v1.dtos.upload.UploadDeleteDTO",
    "backoffice.v1.dtos.upload.UploadDeleteResponseDTO",
    "backoffice.v1.dtos.upload.UploadInitDTO",
    "backoffice.v1.dtos.upload.UploadInitResponseDTO",
    "backoffice.v1.dtos.upload.UploadTargetEnum",
    "backoffice.v1.dtos.user.ListUsersQueryDTO",
    "backoffice.v1.dtos.user.UserCreateDTO",
    "backoffice.v1.dtos.user.UserDTO",
    "backoffice.v1.dtos.user.UserExtDTO",
    "backoffice.v1.dtos.user.UserMinDTO",
    "backoffice.v1.dtos.user.UserWithSponsorCreateDTO",
    "backoffice.v1.dtos.user.UserWithSponsorDTO",
    "backoffice.v1.dtos.user.UserWithSponsorUpdateDTO"
})
public final class NativeReflectionConfig {
  private NativeReflectionConfig() {}
}
