# DATABASE CONFIG
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = neondb_owner
quarkus.datasource.password = npg_dorT8WAEhq5a
quarkus.datasource.jdbc.url = jdbc:postgresql://ep-royal-breeze-acg4wawv-pooler.sa-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_dorT8WAEhq5a&sslmode=require&channelBinding=require

# drop and create the database at startup (use `update` to only update the schema)
# quarkus.hibernate-orm.database.generation = drop-and-create
quarkus.hibernate-orm.database.generation = update
# quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.packages=backoffice.v1.entities
quarkus.datasource.jdbc.driver=org.postgresql.Driver

# TABLE NAMING SNAKE CASE
quarkus.hibernate-orm.physical-naming-strategy=backoffice.common.config.SnakeCasePhysicalNamingStrategy

# JWT TOKEN
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
quarkus.native.resources.includes=publicKey.pem,privateKey.pem
mp.jwt.verify.issuer=sign-in

# Endpoints públicos (sem autenticação)
quarkus.http.auth.permission.public.paths=/v1/auth
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.public.methods=POST

# Garante que endpoints sejam protegidos por padrão
quarkus.http.auth.permission.default.paths=/*
quarkus.http.auth.permission.default.policy=authenticated

# Display logs
quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".min-level=TRACE