# QUARKUS CONFIG
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${CORS_ORIGINS}
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.packages=backoffice.v1.entities
quarkus.datasource.jdbc.driver=org.postgresql.Driver

# TABLE NAMING SNAKE CASE
quarkus.hibernate-orm.physical-naming-strategy=backoffice.common.config.SnakeCasePhysicalNamingStrategy

# JWT TOKEN
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
quarkus.native.resources.includes=publicKey.pem,privateKey.pem
mp.jwt.verify.issuer=sign-in

# Endpoints públicos (sem autenticação)
quarkus.http.auth.permission.public.paths=/v1/auth
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.public.methods=POST

quarkus.http.auth.permission.public-v1.paths=/v1/public/*
quarkus.http.auth.permission.public-v1.policy=permit

# Garante que endpoints sejam protegidos por padrão
quarkus.http.auth.permission.default.paths=/*
quarkus.http.auth.permission.default.policy=authenticated

# Display logs
quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".min-level=TRACE